; $007904..$007A4D | m68k
; Maintained assembly input; no extraction occurs during build.
; JULY LOCAL REVIEW:
; Copy one 80-byte background column into every fourth byte of the software
; viewport, then restore the source/destination cursors for the caller.
        ifne *-$7904
        fail "ROM start moved"
        endif

CopyBackgroundColumn80:
        move.b       (a5)+, (a0)                                   ; $007904
        addq.w       #$4, a0                                       ; $007906
        move.b       (a5)+, (a0)                                   ; $007908
        addq.w       #$4, a0                                       ; $00790A
        move.b       (a5)+, (a0)                                   ; $00790C
        addq.w       #$4, a0                                       ; $00790E
        move.b       (a5)+, (a0)                                   ; $007910
        addq.w       #$4, a0                                       ; $007912
        move.b       (a5)+, (a0)                                   ; $007914
        addq.w       #$4, a0                                       ; $007916
        move.b       (a5)+, (a0)                                   ; $007918
        addq.w       #$4, a0                                       ; $00791A
        move.b       (a5)+, (a0)                                   ; $00791C
        addq.w       #$4, a0                                       ; $00791E
        move.b       (a5)+, (a0)                                   ; $007920
        addq.w       #$4, a0                                       ; $007922
        move.b       (a5)+, (a0)                                   ; $007924
        addq.w       #$4, a0                                       ; $007926
        move.b       (a5)+, (a0)                                   ; $007928
        addq.w       #$4, a0                                       ; $00792A
        move.b       (a5)+, (a0)                                   ; $00792C
        addq.w       #$4, a0                                       ; $00792E
        move.b       (a5)+, (a0)                                   ; $007930
        addq.w       #$4, a0                                       ; $007932
        move.b       (a5)+, (a0)                                   ; $007934
        addq.w       #$4, a0                                       ; $007936
        move.b       (a5)+, (a0)                                   ; $007938
        addq.w       #$4, a0                                       ; $00793A
        move.b       (a5)+, (a0)                                   ; $00793C
        addq.w       #$4, a0                                       ; $00793E
        move.b       (a5)+, (a0)                                   ; $007940
        addq.w       #$4, a0                                       ; $007942
        move.b       (a5)+, (a0)                                   ; $007944
        addq.w       #$4, a0                                       ; $007946
        move.b       (a5)+, (a0)                                   ; $007948
        addq.w       #$4, a0                                       ; $00794A
        move.b       (a5)+, (a0)                                   ; $00794C
        addq.w       #$4, a0                                       ; $00794E
        move.b       (a5)+, (a0)                                   ; $007950
        addq.w       #$4, a0                                       ; $007952
        move.b       (a5)+, (a0)                                   ; $007954
        addq.w       #$4, a0                                       ; $007956
        move.b       (a5)+, (a0)                                   ; $007958
        addq.w       #$4, a0                                       ; $00795A
        move.b       (a5)+, (a0)                                   ; $00795C
        addq.w       #$4, a0                                       ; $00795E
        move.b       (a5)+, (a0)                                   ; $007960
        addq.w       #$4, a0                                       ; $007962
        move.b       (a5)+, (a0)                                   ; $007964
        addq.w       #$4, a0                                       ; $007966
        move.b       (a5)+, (a0)                                   ; $007968
        addq.w       #$4, a0                                       ; $00796A
        move.b       (a5)+, (a0)                                   ; $00796C
        addq.w       #$4, a0                                       ; $00796E
        move.b       (a5)+, (a0)                                   ; $007970
        addq.w       #$4, a0                                       ; $007972
        move.b       (a5)+, (a0)                                   ; $007974
        addq.w       #$4, a0                                       ; $007976
        move.b       (a5)+, (a0)                                   ; $007978
        addq.w       #$4, a0                                       ; $00797A
        move.b       (a5)+, (a0)                                   ; $00797C
        addq.w       #$4, a0                                       ; $00797E
        move.b       (a5)+, (a0)                                   ; $007980
        addq.w       #$4, a0                                       ; $007982
        move.b       (a5)+, (a0)                                   ; $007984
        addq.w       #$4, a0                                       ; $007986
        move.b       (a5)+, (a0)                                   ; $007988
        addq.w       #$4, a0                                       ; $00798A
        move.b       (a5)+, (a0)                                   ; $00798C
        addq.w       #$4, a0                                       ; $00798E
        move.b       (a5)+, (a0)                                   ; $007990
        addq.w       #$4, a0                                       ; $007992
        move.b       (a5)+, (a0)                                   ; $007994
        addq.w       #$4, a0                                       ; $007996
        move.b       (a5)+, (a0)                                   ; $007998
        addq.w       #$4, a0                                       ; $00799A
        move.b       (a5)+, (a0)                                   ; $00799C
        addq.w       #$4, a0                                       ; $00799E
        move.b       (a5)+, (a0)                                   ; $0079A0
        addq.w       #$4, a0                                       ; $0079A2
        move.b       (a5)+, (a0)                                   ; $0079A4
        addq.w       #$4, a0                                       ; $0079A6
        move.b       (a5)+, (a0)                                   ; $0079A8
        addq.w       #$4, a0                                       ; $0079AA
        move.b       (a5)+, (a0)                                   ; $0079AC
        addq.w       #$4, a0                                       ; $0079AE
        move.b       (a5)+, (a0)                                   ; $0079B0
        addq.w       #$4, a0                                       ; $0079B2
        move.b       (a5)+, (a0)                                   ; $0079B4
        addq.w       #$4, a0                                       ; $0079B6
        move.b       (a5)+, (a0)                                   ; $0079B8
        addq.w       #$4, a0                                       ; $0079BA
        move.b       (a5)+, (a0)                                   ; $0079BC
        addq.w       #$4, a0                                       ; $0079BE
        move.b       (a5)+, (a0)                                   ; $0079C0
        addq.w       #$4, a0                                       ; $0079C2
        move.b       (a5)+, (a0)                                   ; $0079C4
        addq.w       #$4, a0                                       ; $0079C6
        move.b       (a5)+, (a0)                                   ; $0079C8
        addq.w       #$4, a0                                       ; $0079CA
        move.b       (a5)+, (a0)                                   ; $0079CC
        addq.w       #$4, a0                                       ; $0079CE
        move.b       (a5)+, (a0)                                   ; $0079D0
        addq.w       #$4, a0                                       ; $0079D2
        move.b       (a5)+, (a0)                                   ; $0079D4
        addq.w       #$4, a0                                       ; $0079D6
        move.b       (a5)+, (a0)                                   ; $0079D8
        addq.w       #$4, a0                                       ; $0079DA
        move.b       (a5)+, (a0)                                   ; $0079DC
        addq.w       #$4, a0                                       ; $0079DE
        move.b       (a5)+, (a0)                                   ; $0079E0
        addq.w       #$4, a0                                       ; $0079E2
        move.b       (a5)+, (a0)                                   ; $0079E4
        addq.w       #$4, a0                                       ; $0079E6
        move.b       (a5)+, (a0)                                   ; $0079E8
        addq.w       #$4, a0                                       ; $0079EA
        move.b       (a5)+, (a0)                                   ; $0079EC
        addq.w       #$4, a0                                       ; $0079EE
        move.b       (a5)+, (a0)                                   ; $0079F0
        addq.w       #$4, a0                                       ; $0079F2
        move.b       (a5)+, (a0)                                   ; $0079F4
        addq.w       #$4, a0                                       ; $0079F6
        move.b       (a5)+, (a0)                                   ; $0079F8
        addq.w       #$4, a0                                       ; $0079FA
        move.b       (a5)+, (a0)                                   ; $0079FC
        addq.w       #$4, a0                                       ; $0079FE
        move.b       (a5)+, (a0)                                   ; $007A00
        addq.w       #$4, a0                                       ; $007A02
        move.b       (a5)+, (a0)                                   ; $007A04
        addq.w       #$4, a0                                       ; $007A06
        move.b       (a5)+, (a0)                                   ; $007A08
        addq.w       #$4, a0                                       ; $007A0A
        move.b       (a5)+, (a0)                                   ; $007A0C
        addq.w       #$4, a0                                       ; $007A0E
        move.b       (a5)+, (a0)                                   ; $007A10
        addq.w       #$4, a0                                       ; $007A12
        move.b       (a5)+, (a0)                                   ; $007A14
        addq.w       #$4, a0                                       ; $007A16
        move.b       (a5)+, (a0)                                   ; $007A18
        addq.w       #$4, a0                                       ; $007A1A
        move.b       (a5)+, (a0)                                   ; $007A1C
        addq.w       #$4, a0                                       ; $007A1E
        move.b       (a5)+, (a0)                                   ; $007A20
        addq.w       #$4, a0                                       ; $007A22
        move.b       (a5)+, (a0)                                   ; $007A24
        addq.w       #$4, a0                                       ; $007A26
        move.b       (a5)+, (a0)                                   ; $007A28
        addq.w       #$4, a0                                       ; $007A2A
        move.b       (a5)+, (a0)                                   ; $007A2C
        addq.w       #$4, a0                                       ; $007A2E
        move.b       (a5)+, (a0)                                   ; $007A30
        addq.w       #$4, a0                                       ; $007A32
        move.b       (a5)+, (a0)                                   ; $007A34
        addq.w       #$4, a0                                       ; $007A36
        move.b       (a5)+, (a0)                                   ; $007A38
        addq.w       #$4, a0                                       ; $007A3A
        move.b       (a5)+, (a0)                                   ; $007A3C
        addq.w       #$4, a0                                       ; $007A3E
        move.b       (a5)+, (a0)                                   ; $007A40
        addq.w       #$4, a0                                       ; $007A42
        lea.l        -SceneBackgroundColumnBytes(a5), a5          ; $007A44
        lea.l        -SoftwareFrameColumnSpan(a0), a0              ; $007A48
        rts                                                        ; $007A4C
        ifne *-$7A4E
        fail "ROM end moved"
        endif
